version: "3.7"

services:
  postgres:
    restart: unless-stopped
    image: postgres:16.0
    volumes:
      - postgres_db:/var/lib/postgresql/data
    env_file:
      - backend/app/.env

  backend:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    env_file:
      - backend/app/.env
    ports:
      - 8000:8000
    volumes:
      - ./backend/app:/app
    depends_on:
      - postgres

volumes:
  postgres_db:
